### ISSUE TITLE
Snabb Switch experience

### ISSUE THREAD

**Issue by lukego** [pybee/paying-the-piper#10]
In the [Snabb Switch](https://github.com/SnabbCo/snabbswitch/) community we have been exploring ways to sustainably fuel development. The first braindump was [Snabb Switch for Entrepreneurs](https://github.com/SnabbCo/snabbswitch/wiki/Snabb-Switch-for-Entrepreneurs) and our early experience so far is pretty positive.

We are in the networking industry. Big companies use our software as an alternative to spending millions of dollars on license fees to vendors like Cisco. Smaller companies use our software as an alternative to being neglected by vendors. Service providers (individuals, small companies, big companies) cooperate to deliver projects to users in the form of "provide functionality X on date Y."

The project has a little economy growing organically around it. I think about this in terms of GNP (money entering the ecosystem) and GDP (money circulating within the ecosystem). In both cases it doesn't matter _who_ is paying for and delivering the services: it just matters that somebody is doing this and that activity is growing to create opportunities for new people. (There is no central person or commercial entity that we need to feed money to either now or in the future.)

Money enters the ecosystem in a few ways:
1. End-user company buys services related to the project. This could be to build a whole product as open source (years of effort), to make some modest customizations (months of effort), or to provide support or training (perhaps ongoingly).
2. People who are already employed decide to contribute to the project as part of their job. This could be an end-user who wants to use the software to solve problems in their own network or it could be somebody is a vendor who wants to use the software as part of a larger solution.
3. Service providers invest their own time in building a reputation and creating new opportunities for themselves.
4. Organizations such as NLnet sponsor people to make contributions to the project.

Money circulates within the ecosystem when service providers cooperate to deliver projects. There is no single services company in our community: rather there are many people and companies of different shapes and sizes who cooperate on projects. There are also no barriers to entry within this ecosystem: anybody can make an offer along the lines of "I will provide functionality X on date Y" or "I will spend Z weeks working on this project" and everybody is free to decide who to work with.

Currently this is working out fairly well. Gradually we are gaining more service-providers, more user-contributors, and more user-customers. There are positive network effects where each successful project expands the set of problems we can attack with confidence.

There is a long way to go though :). I would estimate that we are now less than 100 people using and developing the software in a professional context. Quite a bit of our work is interconnected. Over time we need to build a robust and decentralized commercial ecosystem like the one surrounding the Linux kernel. This takes time and our strategy is to keep growing at an organic pace.

I hope that braindump on our experience is of some use to somebody!

**Comment by freakboy3742** [comment]
Thanks for the braindump! The GNP/GDP analogy is a good one; to continue the analogy, the effect of the exogenous spending multiplier on growth can't be underestimated.

It sounds like there's an analog here with something like a web framework, in that many many people want a web site developed; but in order for that to happen, a web framework needs to exist. In the web space, most of the money exists in the "solving problems" space; it's harder to find money for directly working on the tools.

Is this how it works for Snabb Switch? Is there anyone in the community that earns 100% of their income from working _on_ Snabb Switch, rather than more broadly on community activity? 

Also - how was this community bootstrapped?

**Comment by lukego** [comment]
Answered on [another thread](https://github.com/pybee/paying-the-piper/issues/15#issuecomment-148602986).

**Comment by lukego** [comment]
(Has been discussed.)
