### ISSUE TITLE
Don't use money to estimate the value

### ISSUE THREAD

**Issue by techtonik** [pybee/paying-the-piper#16]
Economy needs balance. In computer games you can not balance the gameplay using only single kind of resources - gold. There are always at least three types of resources to keep things playable. Otherwise any game becomes a money hoarder game. This makes money a player's goal, as it already happens in current economy. 

Bigger economy always eats lesser one. If you use money that is the main (and the only?) resource of current economy, you have no chance to stand over it. That system has a good protection mechanisms evolved at least through one century, so be prepared to met them (Gratipocalypse). Decoupling money from value is a must.

Gratipay 1.0 had made a good progress towards that - you could use a little sum, to say $1 donated to you by others, to redistribute the value as little as $0.01 to people who you find important. For me it was "Python mana" - I used to tag people based on how important they were to me. Thinking that they could buy a beer for that (not a healthy choice, but still) was fun to play with. In the end Gratipay 1.0 contained a graph of how different people were useful to each other. We never exported this graph and I will never have time to work on that, but that was the idea.

The graph can be used for different things. For example, when somebody leaves the community to join big company, that company may choose to compensate the community the loss of its member (his switch to passive) using this graph as a redistribution ratio.

Then the flow starts, people know how much do they need, so they will have the choice to redirect the flow after it exceeds their basic needs to other people. This requires them to know they basic needs requirements, which increases when they have families and rents. Sum of all means is the basic capacity. Capacity means how much people can this economy support.

**Comment by freakboy3742** [comment]
This isn't an abstract discussion about "value" - it's a simple, practical discussion about how I can feed my children without burning out. 

While there was much to like in the Gratipay model, it also suffered by focussing on the micro level. That put the focus of fundraising on the individual, rather than the corporations who are actually generating profits on the back of open source projects. 

I know there was nothing preventing companies from joining Gratipay as donors, but the focus on individual donors and donating small sums framed the perception of the service.

**Comment by techtonik** [comment]
@freakboy3742 you've missed the point. Corporation can't estimate the value of open source back in their bottom line. The redistribution graph provides the way for them to be Socially Responsible in front on Open Source Community.

Unfortunately, the economics is more complex than necessary to feed your children.
