### ISSUE TITLE
How do I give you money?

### ISSUE THREAD

**Issue by jefftriplett** [pybee/paying-the-piper#17]
Please shut up and take my money. Seriously, giving your project money needs to be easy. Options:
- [Patreon](https://www.patreon.com) Example: [DjangoGirls](https://www.patreon.com/djangogirls?ty=c)
- [Square Cash](https://cash.me/)
- PayPal? (not linked because...)

**Comment by seiyria** [comment]
Stripe is great too!

**Comment by lukego** [comment]
Interestingly not everybody wants money from random people to work on open source. I was surprised the first time I tried to contribute money to a project only to be told they don't take donations from private people. People who want to be paid to work on open source need to be clear about _who_ they want to pay them (which might not include you or me).

**Comment by freakboy3742** [comment]
@lukego That's a good point - although the reason _why_ is also important. For example, if I'm working full time for another company, and don't really want to change jobs, getting beer money donated is usually more trouble than it's worth to manage from a tax perspective. 

If I was able to track how many people _wanted_ to give me money, without actually taking it, that might make it easier to make the decision to take the plunge and start doing open source full time.

**Comment by beltiras** [comment]
Kickstarter model seems like a good place to start.

**Comment by jefftriplett** [comment]
Crowdfunding is fine, covered in #3  -- However it misses the bigger picture of sustainability. You have a great oppurtunity when someone is on your website / project page and is willing to give you money to get their money to support your efforts. This should be easier and Patreon does a pretty good job from a user experience perspective. I'm already supporting Django Girls using it so supporting more communities / individuals through it is easier and only one charge to check each month.
