### ISSUE TITLE
Promote the Two Day Manifesto at your company

### ISSUE THREAD

**Issue by nchammas** [pybee/paying-the-piper#62]
This suggestion is more about making open source development sustainable, rather than directly funding it. Funding is one possible approach to making development sustainable, but it can and should be complemented by other approaches.

Promote the [Two Day Manifesto](http://twodaymanifesto.com/) at your company:

> Each developer in your company should have at least two days per month to work on the open source software your product is built on.

I think it's possible for something like this to start off as a selling point for companies and teams looking to hire, and grow from there into an accepted norm in technology jobs. It wouldn't obviate the need for funding, but it would definitely help open source communities if their corporate users were better empowered to give back.

I believe @drmaciver is the author of the Two Day Manifesto. [Here's the repo backing the site](https://github.com/TwoDayManifesto/twodaymanifesto.github.io).

Adapted from my comment on @nedbat's [blog post](http://nedbatchelder.com//blog/201511/funding_free_software.html).
cc @twneale

**Comment by nchammas** [comment]
Just read through the discussion in #15. It looks like this repo is exclusively focused on funding open source development, so my suggestion here is probably off-topic.

I guess it's already quite clear from the repo name and description what the focus of discussion is, but perhaps the README should be updated to explicitly call out other approaches as off topic.

**Comment by freakboy3742** [comment]
@nchammas That's a good idea. "Two Day Manifesto" is a great idea, and certainly a welcome addition to the mix; but the problem I'm trying to address here isn't extracting little bits of labour - it's funding the grand activities (large scale permanent project development and maintenance, etc).

**Comment by nchammas** [comment]
Yep, I gathered as much after reading through #15.
